ALTER TABLE horses
  ADD COLUMN IF NOT EXISTS vet_name VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS vet_phone VARCHAR(100) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS farrier_name VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS farrier_phone VARCHAR(100) NOT NULL DEFAULT '';
